use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let dir = ctx.paths.config_home.join("alacritty");
    let generated = dir.join("irongall.toml");
    ctx.write_file(&generated, &generated_toml(ctx))?;

    let toml_path = dir.join("alacritty.toml");
    let yml_path = dir.join("alacritty.yml");

    if yml_path.exists() && !toml_path.exists() {
        let body = colors_yaml(ctx);
        ctx.patch_file(&yml_path, &body, CommentStyle::Hash, false)?;
        return Ok(done(ctx, "alacritty.yml markers"));
    }

    let existing = std::fs::read_to_string(&toml_path).unwrap_or_default();
    let uses_import = existing.contains("import") || existing.contains("general.import");
    if uses_import || !toml_path.exists() {
        let body = "general.import = [\"~/.config/alacritty/irongall.toml\"]";
        // If they already import other files, still append ours via markers.
        let body = if existing.contains("irongall.toml") {
            "# irongall.toml already imported"
        } else {
            body
        };
        ctx.patch_file(&toml_path, body, CommentStyle::Hash, true)?;
        return Ok(done(ctx, "import irongall.toml"));
    }

    let body = generated_toml(ctx);
    ctx.patch_file(&toml_path, &body, CommentStyle::Hash, true)?;
    Ok(done(ctx, "alacritty.toml markers"))
}

fn generated_toml(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let ansi = p.ansi16();
    let size = crate::config::format_pt(ctx.effective.size);
    let mut s = String::from("# generated by irongall — do not edit\n");
    s.push_str(&format!(
        "[font]\nnormal = {{ family = \"{}\" }}\nsize = {size}\n\n",
        ctx.effective.font
    ));
    s.push_str("[colors.primary]\n");
    s.push_str(&format!("background = \"{}\"\n", p.base00().hex_lower()));
    s.push_str(&format!("foreground = \"{}\"\n\n", p.base05().hex_lower()));
    s.push_str("[colors.cursor]\n");
    s.push_str(&format!("text = \"{}\"\n", p.base00().hex_lower()));
    s.push_str(&format!("cursor = \"{}\"\n\n", p.base05().hex_lower()));
    s.push_str("[colors.selection]\n");
    s.push_str(&format!("text = \"{}\"\n", p.base05().hex_lower()));
    s.push_str(&format!(
        "background = \"{}\"\n\n",
        p.base02().hex_lower()
    ));
    s.push_str("[colors.normal]\n");
    s.push_str(&format!("black = \"{}\"\n", ansi[0].hex_lower()));
    s.push_str(&format!("red = \"{}\"\n", ansi[1].hex_lower()));
    s.push_str(&format!("green = \"{}\"\n", ansi[2].hex_lower()));
    s.push_str(&format!("yellow = \"{}\"\n", ansi[3].hex_lower()));
    s.push_str(&format!("blue = \"{}\"\n", ansi[4].hex_lower()));
    s.push_str(&format!("magenta = \"{}\"\n", ansi[5].hex_lower()));
    s.push_str(&format!("cyan = \"{}\"\n", ansi[6].hex_lower()));
    s.push_str(&format!("white = \"{}\"\n\n", ansi[7].hex_lower()));
    s.push_str("[colors.bright]\n");
    s.push_str(&format!("black = \"{}\"\n", ansi[8].hex_lower()));
    s.push_str(&format!("red = \"{}\"\n", ansi[9].hex_lower()));
    s.push_str(&format!("green = \"{}\"\n", ansi[10].hex_lower()));
    s.push_str(&format!("yellow = \"{}\"\n", ansi[11].hex_lower()));
    s.push_str(&format!("blue = \"{}\"\n", ansi[12].hex_lower()));
    s.push_str(&format!("magenta = \"{}\"\n", ansi[13].hex_lower()));
    s.push_str(&format!("cyan = \"{}\"\n", ansi[14].hex_lower()));
    s.push_str(&format!("white = \"{}\"\n", ansi[15].hex_lower()));
    s
}

fn colors_yaml(ctx: &ApplyCtx<'_>) -> String {
    // Legacy yaml: emit the same values as comments + a generated include hint.
    generated_toml(ctx)
}

fn done(ctx: &ApplyCtx<'_>, d: &str) -> TargetStatus {
    if ctx.dry_run {
        TargetStatus::DryRun {
            summary: d.into(),
        }
    } else {
        TargetStatus::Ok {
            detail: Some(d.into()),
        }
    }
}
