use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let dir = ctx.paths.config_home.join("btop");
    let theme_path = dir.join("themes/irongall.theme");
    ctx.write_file(&theme_path, &theme(ctx))?;
    let conf = dir.join("btop.conf");
    ctx.patch_file(&conf, "color_theme = \"irongall\"", CommentStyle::Hash, true)?;
    Ok(if ctx.dry_run {
        TargetStatus::DryRun {
            summary: "btop theme".into(),
        }
    } else {
        TargetStatus::Ok {
            detail: Some("theme".into()),
        }
    })
}

fn theme(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let bg = p.base00().hex_lower();
    let fg = p.base05().hex_lower();
    let acc = p.accent().hex_lower();
    let red = p.base08().hex_lower();
    let blu = p.base0d().hex_lower();
    let dim = p.base04().hex_lower();
    let sel = p.base02().hex_lower();
    let b03 = p.base03().hex_lower();
    format!(
        "# generated by irongall — do not edit\n\
         theme[main_bg]=\"{bg}\"\n\
         theme[main_fg]=\"{fg}\"\n\
         theme[title]=\"{red}\"\n\
         theme[hi_fg]=\"{acc}\"\n\
         theme[selected_bg]=\"{sel}\"\n\
         theme[selected_fg]=\"{fg}\"\n\
         theme[inactive_fg]=\"{b03}\"\n\
         theme[proc_misc]=\"{blu}\"\n\
         theme[cpu_box]=\"{dim}\"\n\
         theme[mem_box]=\"{dim}\"\n\
         theme[net_box]=\"{dim}\"\n\
         theme[proc_box]=\"{dim}\"\n\
         theme[div_line]=\"{b03}\"\n\
         theme[temp_start]=\"{red}\"\n\
         theme[temp_mid]=\"{blu}\"\n\
         theme[temp_end]=\"{acc}\"\n\
         theme[cpu_start]=\"{red}\"\n\
         theme[cpu_mid]=\"{blu}\"\n\
         theme[cpu_end]=\"{acc}\"\n\
         theme[free_start]=\"{red}\"\n\
         theme[free_mid]=\"{blu}\"\n\
         theme[free_end]=\"{acc}\"\n\
         theme[cached_start]=\"{red}\"\n\
         theme[cached_mid]=\"{blu}\"\n\
         theme[cached_end]=\"{acc}\"\n\
         theme[available_start]=\"{red}\"\n\
         theme[available_mid]=\"{blu}\"\n\
         theme[available_end]=\"{acc}\"\n\
         theme[used_start]=\"{red}\"\n\
         theme[used_mid]=\"{blu}\"\n\
         theme[used_end]=\"{acc}\"\n\
         theme[download_start]=\"{red}\"\n\
         theme[download_mid]=\"{blu}\"\n\
         theme[download_end]=\"{acc}\"\n\
         theme[upload_start]=\"{red}\"\n\
         theme[upload_mid]=\"{blu}\"\n\
         theme[upload_end]=\"{acc}\"\n"
    )
}
