use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let dir = ctx.paths.config_home.join("helix");
    let theme_path = dir.join("themes/irongall.toml");
    ctx.write_file(&theme_path, &theme_toml(ctx))?;

    let conf = dir.join("config.toml");
    let body = "theme = \"irongall\"";
    ctx.patch_file(&conf, body, CommentStyle::Hash, true)?;
    Ok(if ctx.dry_run {
        TargetStatus::DryRun {
            summary: "theme irongall".into(),
        }
    } else {
        TargetStatus::Ok {
            detail: Some("theme".into()),
        }
    })
}

fn theme_toml(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    format!(
        "# generated by irongall — do not edit\n\
         \"ui.background\" = {{ bg = \"base00\" }}\n\
         \"ui.text\" = \"base05\"\n\
         \"ui.cursor\" = {{ fg = \"base00\", bg = \"base05\" }}\n\
         \"ui.selection\" = {{ bg = \"base02\" }}\n\
         \"ui.linenr\" = \"base03\"\n\
         \"ui.linenr.selected\" = \"base04\"\n\
         \"ui.statusline\" = {{ fg = \"base04\", bg = \"base01\" }}\n\
         \"ui.menu\" = {{ fg = \"base05\", bg = \"base01\" }}\n\
         \"ui.menu.selected\" = {{ fg = \"base01\", bg = \"base05\" }}\n\
         \"comment\" = \"base03\"\n\
         \"string\" = \"base0B\"\n\
         \"keyword\" = \"base0E\"\n\
         \"function\" = \"base0D\"\n\
         \"type\" = \"base0A\"\n\
         \"constant\" = \"base09\"\n\
         \"variable\" = \"base05\"\n\
         \"error\" = \"base08\"\n\
         \"warning\" = \"base09\"\n\
         \n\
         [palette]\n\
         base00 = \"{b00}\"\n\
         base01 = \"{b01}\"\n\
         base02 = \"{b02}\"\n\
         base03 = \"{b03}\"\n\
         base04 = \"{b04}\"\n\
         base05 = \"{b05}\"\n\
         base06 = \"{b06}\"\n\
         base07 = \"{b07}\"\n\
         base08 = \"{b08}\"\n\
         base09 = \"{b09}\"\n\
         base0A = \"{b0a}\"\n\
         base0B = \"{b0b}\"\n\
         base0C = \"{b0c}\"\n\
         base0D = \"{b0d}\"\n\
         base0E = \"{b0e}\"\n\
         base0F = \"{b0f}\"\n",
        b00 = p.base00().hex_lower(),
        b01 = p.base01().hex_lower(),
        b02 = p.base02().hex_lower(),
        b03 = p.base03().hex_lower(),
        b04 = p.base04().hex_lower(),
        b05 = p.base05().hex_lower(),
        b06 = p.base06().hex_lower(),
        b07 = p.base07().hex_lower(),
        b08 = p.base08().hex_lower(),
        b09 = p.base09().hex_lower(),
        b0a = p.base0a().hex_lower(),
        b0b = p.base0b().hex_lower(),
        b0c = p.base0c().hex_lower(),
        b0d = p.base0d().hex_lower(),
        b0e = p.base0e().hex_lower(),
        b0f = p.base0f().hex_lower(),
    )
}
