use std::process::Command;

use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::font;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let theme_dir = ctx.paths.config_home.join("kitty/themes");
    let theme_path = theme_dir.join("irongall.conf");
    ctx.write_file(&theme_path, &theme_file(ctx))?;

    let conf = ctx.paths.config_home.join("kitty/kitty.conf");
    let mut body = String::new();
    body.push_str("include themes/irongall.conf\n");
    body.push_str(&format!("font_family {}\n", ctx.effective.font));
    body.push_str(&format!(
        "font_size {}\n",
        crate::config::format_pt(ctx.effective.size)
    ));
    body.push_str("disable_ligatures never\n");
    if let Some(nerd) = font::detect_nerd_font() {
        body.push_str(&format!(
            "symbol_map U+E000-U+F8FF,U+F0000-U+F1FFF {nerd}\n"
        ));
    }
    ctx.patch_file(&conf, &body, CommentStyle::Hash, true)?;

    let mut detail = "theme include".to_string();
    if !ctx.dry_run {
        let _ = Command::new("pkill").args(["-USR1", "kitty"]).status();
        detail.push_str(", reloaded");
    }
    Ok(if ctx.dry_run {
        TargetStatus::DryRun { summary: detail }
    } else {
        TargetStatus::Ok { detail: Some(detail) }
    })
}

fn theme_file(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let ansi = p.ansi16();
    let mut s = String::from("# generated by irongall — do not edit\n");
    s.push_str(&format!("foreground {}\n", p.base05().hex_lower()));
    s.push_str(&format!("background {}\n", p.base00().hex_lower()));
    s.push_str(&format!("cursor {}\n", p.base05().hex_lower()));
    s.push_str(&format!("selection_background {}\n", p.base02().hex_lower()));
    s.push_str(&format!("selection_foreground {}\n", p.base05().hex_lower()));
    s.push_str(&format!("url_color {}\n", p.base0d().hex_lower()));
    for (i, c) in ansi.iter().enumerate() {
        s.push_str(&format!("color{i} {}\n", c.hex_lower()));
    }
    s
}
