use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let nvim = ctx.paths.config_home.join("nvim");
    if !nvim.exists() {
        return Ok(TargetStatus::Skipped {
            reason: "no ~/.config/nvim".into(),
        });
    }

    let lua = nvim.join("lua/irongall.lua");
    ctx.write_file(&lua, &colorscheme(ctx))?;

    let require_line = "pcall(require, \"irongall\")";
    let init_lua = nvim.join("init.lua");
    let options_lua = nvim.join("lua/options.lua");
    let init_vim = nvim.join("init.vim");

    if init_lua.exists() {
        ctx.patch_file(&init_lua, require_line, CommentStyle::Lua, false)?;
    } else if options_lua.exists() {
        ctx.patch_file(&options_lua, require_line, CommentStyle::Lua, false)?;
    } else if init_vim.exists() {
        let body = "lua pcall(require, \"irongall\")";
        ctx.patch_file(&init_vim, body, CommentStyle::Vim, false)?;
    } else {
        ctx.patch_file(&init_lua, require_line, CommentStyle::Lua, true)?;
    }

    Ok(if ctx.dry_run {
        TargetStatus::DryRun {
            summary: "lua/irongall.lua".into(),
        }
    } else {
        TargetStatus::Ok {
            detail: Some("lua/irongall.lua".into()),
        }
    })
}

fn colorscheme(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let size = crate::config::format_pt(ctx.effective.size);
    format!(
        "-- generated by irongall — do not edit\n\
         -- A standalone base16 colorscheme. LazyVim-safe: only required\n\
         -- from a one-line IRONGALL marker in init.lua / options.lua.\n\
         vim.opt.termguicolors = true\n\
         vim.opt.guifont = \"{font}:h{size}\"\n\
         vim.g.colors_name = \"irongall\"\n\
         \n\
         local p = {{\n\
           base00 = \"{b00}\", base01 = \"{b01}\", base02 = \"{b02}\", base03 = \"{b03}\",\n\
           base04 = \"{b04}\", base05 = \"{b05}\", base06 = \"{b06}\", base07 = \"{b07}\",\n\
           base08 = \"{b08}\", base09 = \"{b09}\", base0A = \"{b0a}\", base0B = \"{b0b}\",\n\
           base0C = \"{b0c}\", base0D = \"{b0d}\", base0E = \"{b0e}\", base0F = \"{b0f}\",\n\
         }}\n\
         \n\
         local function hi(group, opts)\n\
           vim.api.nvim_set_hl(0, group, opts)\n\
         end\n\
         \n\
         hi(\"Normal\",       {{ fg = p.base05, bg = p.base00 }})\n\
         hi(\"Comment\",      {{ fg = p.base03, italic = true }})\n\
         hi(\"Constant\",     {{ fg = p.base09 }})\n\
         hi(\"String\",       {{ fg = p.base0B }})\n\
         hi(\"Identifier\",   {{ fg = p.base08 }})\n\
         hi(\"Function\",     {{ fg = p.base0D }})\n\
         hi(\"Statement\",    {{ fg = p.base0E }})\n\
         hi(\"Keyword\",      {{ fg = p.base0E }})\n\
         hi(\"PreProc\",      {{ fg = p.base0A }})\n\
         hi(\"Type\",         {{ fg = p.base0A }})\n\
         hi(\"Special\",      {{ fg = p.base0C }})\n\
         hi(\"Error\",        {{ fg = p.base08, bold = true }})\n\
         hi(\"Todo\",         {{ fg = p.base0A, bold = true }})\n\
         hi(\"LineNr\",       {{ fg = p.base03, bg = p.base00 }})\n\
         hi(\"CursorLine\",   {{ bg = p.base01 }})\n\
         hi(\"CursorLineNr\", {{ fg = p.base04, bg = p.base01 }})\n\
         hi(\"Visual\",       {{ bg = p.base02 }})\n\
         hi(\"Search\",       {{ fg = p.base00, bg = p.base0A }})\n\
         hi(\"IncSearch\",    {{ fg = p.base00, bg = p.base09 }})\n\
         hi(\"Pmenu\",        {{ fg = p.base05, bg = p.base01 }})\n\
         hi(\"PmenuSel\",     {{ fg = p.base01, bg = p.base05 }})\n\
         hi(\"StatusLine\",   {{ fg = p.base04, bg = p.base01 }})\n\
         hi(\"StatusLineNC\", {{ fg = p.base03, bg = p.base01 }})\n\
         hi(\"VertSplit\",    {{ fg = p.base02, bg = p.base00 }})\n\
         hi(\"WinSeparator\", {{ fg = p.base02 }})\n\
         hi(\"TabLine\",      {{ fg = p.base03, bg = p.base01 }})\n\
         hi(\"TabLineSel\",   {{ fg = p.base05, bg = p.base00 }})\n\
         hi(\"Title\",        {{ fg = p.base0D, bold = true }})\n\
         hi(\"DiffAdd\",      {{ fg = p.base0B, bg = p.base00 }})\n\
         hi(\"DiffChange\",   {{ fg = p.base0A, bg = p.base00 }})\n\
         hi(\"DiffDelete\",   {{ fg = p.base08, bg = p.base00 }})\n\
         hi(\"DiffText\",     {{ fg = p.base0D, bg = p.base00 }})\n\
         hi(\"DiagnosticError\", {{ fg = p.base08 }})\n\
         hi(\"DiagnosticWarn\",  {{ fg = p.base0A }})\n\
         hi(\"DiagnosticInfo\",  {{ fg = p.base0D }})\n\
         hi(\"DiagnosticHint\",  {{ fg = p.base0C }})\n\
         hi(\"@keyword\",     {{ fg = p.base0E }})\n\
         hi(\"@string\",      {{ fg = p.base0B }})\n\
         hi(\"@function\",    {{ fg = p.base0D }})\n\
         hi(\"@comment\",     {{ fg = p.base03, italic = true }})\n\
         hi(\"@type\",        {{ fg = p.base0A }})\n\
         hi(\"@variable\",    {{ fg = p.base05 }})\n",
        font = ctx.effective.font.replace('\\', "\\\\").replace('"', "\\\""),
        size = size,
        b00 = p.base00().hex_lower(),
        b01 = p.base01().hex_lower(),
        b02 = p.base02().hex_lower(),
        b03 = p.base03().hex_lower(),
        b04 = p.base04().hex_lower(),
        b05 = p.base05().hex_lower(),
        b06 = p.base06().hex_lower(),
        b07 = p.base07().hex_lower(),
        b08 = p.base08().hex_lower(),
        b09 = p.base09().hex_lower(),
        b0a = p.base0a().hex_lower(),
        b0b = p.base0b().hex_lower(),
        b0c = p.base0c().hex_lower(),
        b0d = p.base0d().hex_lower(),
        b0e = p.base0e().hex_lower(),
        b0f = p.base0f().hex_lower(),
    )
}
