use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let generated = ctx.paths.config_home.join("wezterm/irongall.lua");
    ctx.write_file(&generated, &lua_module(ctx))?;

    let path = if ctx.paths.config_home.join("wezterm/wezterm.lua").exists() {
        ctx.paths.config_home.join("wezterm/wezterm.lua")
    } else if ctx.paths.home.join(".wezterm.lua").exists() {
        ctx.paths.home.join(".wezterm.lua")
    } else {
        ctx.paths.config_home.join("wezterm/wezterm.lua")
    };

    let body = "pcall(function()\n  local ig = dofile(os.getenv(\"HOME\") .. \"/.config/wezterm/irongall.lua\")\n  ig.apply(config)\nend)";
    if !path.exists() {
        let full = format!(
            "local wezterm = require 'wezterm'\nlocal config = wezterm.config_builder and wezterm.config_builder() or {{}}\n\n-- IRONGALL-BEGIN\n{body}\n-- IRONGALL-END\n\nreturn config\n"
        );
        ctx.write_file(&path, &full)?;
    } else {
        ctx.patch_file(&path, body, CommentStyle::Lua, false)?;
    }
    Ok(if ctx.dry_run {
        TargetStatus::DryRun {
            summary: "wezterm.lua".into(),
        }
    } else {
        TargetStatus::Ok { detail: None }
    })
}

fn lua_module(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let ansi = p.ansi16();
    format!(
        "-- generated by irongall — do not edit\n\
         local M = {{}}\n\
         function M.apply(config)\n\
           config.font = require('wezterm').font('{font}')\n\
           config.font_size = {size}\n\
           config.colors = {{\n\
             foreground = '{fg}',\n\
             background = '{bg}',\n\
             cursor_bg = '{fg}',\n\
             cursor_fg = '{bg}',\n\
             selection_bg = '{sel}',\n\
             selection_fg = '{fg}',\n\
             ansi = {ansi},\n\
             brights = {brights},\n\
           }}\n\
         end\n\
         return M\n",
        font = ctx.effective.font.replace('\'', "\\'"),
        size = crate::config::format_pt(ctx.effective.size),
        fg = p.base05().hex_lower(),
        bg = p.base00().hex_lower(),
        sel = p.base02().hex_lower(),
        ansi = lua_list(&ansi[0..8]),
        brights = lua_list(&ansi[8..16]),
    )
}

fn lua_list(cs: &[crate::color::Rgb]) -> String {
    let inner = cs
        .iter()
        .map(|c| format!("'{}'", c.hex_lower()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{{ {inner} }}")
}
