use crate::apply::{ApplyCtx, TargetStatus};
use crate::error::Result;
use crate::markers::CommentStyle;

pub fn apply(ctx: &mut ApplyCtx<'_>) -> Result<TargetStatus> {
    let dir = ctx.paths.config_home.join("yazi");
    let flavor_dir = dir.join("flavors/irongall.yazi");
    ctx.write_file(&flavor_dir.join("flavor.toml"), &flavor(ctx))?;

    let theme = dir.join("theme.toml");
    let body = "[flavor]\ndark = \"irongall\"\nlight = \"irongall\"";
    ctx.patch_file(&theme, body, CommentStyle::Hash, true)?;
    Ok(done(ctx, "flavor irongall"))
}

fn flavor(ctx: &ApplyCtx<'_>) -> String {
    let p = &ctx.scheme.palette;
    let fg = p.base05().hex_lower();
    let bg = p.base00().hex_lower();
    let bg2 = p.base01().hex_lower();
    let dim = p.base03().hex_lower();
    let red = p.base08().hex_lower();
    let yel = p.base0a().hex_lower();
    let grn = p.base0b().hex_lower();
    let cyn = p.base0c().hex_lower();
    let blu = p.base0d().hex_lower();
    let acc = p.accent().hex_lower();
    format!(
        "# generated by irongall — do not edit\n\
         [mgr]\n\
         cwd = {{ fg = \"{fg}\" }}\n\
         hovered = {{ reversed = true }}\n\
         preview_hovered = {{ underline = true }}\n\
         find_keyword = {{ fg = \"{red}\", bold = true, italic = true, underline = true }}\n\
         find_position = {{ fg = \"{red}\", bold = true, italic = true }}\n\
         marker_copied = {{ fg = \"{grn}\", bg = \"{grn}\" }}\n\
         marker_cut = {{ fg = \"{red}\", bg = \"{red}\" }}\n\
         marker_marked = {{ fg = \"{acc}\", bg = \"{acc}\" }}\n\
         marker_selected = {{ fg = \"{blu}\", bg = \"{blu}\" }}\n\
         count_copied = {{ fg = \"{bg}\", bg = \"{grn}\" }}\n\
         count_cut = {{ fg = \"{bg}\", bg = \"{red}\" }}\n\
         count_selected = {{ fg = \"{bg}\", bg = \"{acc}\" }}\n\
         border_style = {{ fg = \"{acc}\" }}\n\
         \n\
         [tab]\n\
         active = {{ fg = \"{bg}\", bg = \"{acc}\", bold = true }}\n\
         inactive = {{ fg = \"{blu}\", bg = \"{bg}\" }}\n\
         \n\
         [status]\n\
         overall = {{ fg = \"{acc}\" }}\n\
         sep_left = {{ open = \"\", close = \"\" }}\n\
         sep_right = {{ open = \"\", close = \"\" }}\n\
         perm_type = {{ fg = \"{blu}\" }}\n\
         perm_read = {{ fg = \"{grn}\" }}\n\
         perm_write = {{ fg = \"{yel}\" }}\n\
         perm_exec = {{ fg = \"{red}\" }}\n\
         perm_sep = {{ fg = \"{dim}\" }}\n\
         progress_label = {{ bold = true }}\n\
         progress_normal = {{ fg = \"{acc}\", bg = \"{bg}\" }}\n\
         progress_error = {{ fg = \"{red}\", bg = \"{bg}\" }}\n\
         \n\
         [mode]\n\
         normal_main = {{ bg = \"{acc}\", fg = \"{bg}\", bold = true }}\n\
         normal_alt = {{ bg = \"{bg2}\", fg = \"{dim}\" }}\n\
         select_main = {{ bg = \"{blu}\", fg = \"{bg}\", bold = true }}\n\
         select_alt = {{ bg = \"{bg2}\", fg = \"{dim}\" }}\n\
         unset_main = {{ bg = \"{acc}\", fg = \"{bg}\", bold = true }}\n\
         unset_alt = {{ bg = \"{bg2}\", fg = \"{dim}\" }}\n\
         \n\
         [input]\n\
         border = {{ fg = \"{acc}\" }}\n\
         value = {{ fg = \"{fg}\" }}\n\
         selected = {{ reversed = true }}\n\
         \n\
         [pick]\n\
         border = {{ fg = \"{acc}\" }}\n\
         active = {{ fg = \"{acc}\", bold = true }}\n\
         inactive = {{}}\n\
         \n\
         [confirm]\n\
         border = {{ fg = \"{acc}\" }}\n\
         title = {{}}\n\
         content = {{}}\n\
         list = {{}}\n\
         btn_yes = {{ reversed = true }}\n\
         btn_no = {{}}\n\
         \n\
         [cmp]\n\
         border = {{ fg = \"{acc}\" }}\n\
         active = {{ reversed = true }}\n\
         inactive = {{}}\n\
         \n\
         [tasks]\n\
         border = {{ fg = \"{acc}\" }}\n\
         title = {{}}\n\
         hovered = {{ fg = \"{acc}\", underline = true }}\n\
         \n\
         [which]\n\
         mask = {{ bg = \"{bg2}\" }}\n\
         cand = {{ fg = \"{cyn}\" }}\n\
         rest = {{ fg = \"{dim}\" }}\n\
         desc = {{ fg = \"{fg}\" }}\n\
         separator = \"  \"\n\
         separator_style = {{ fg = \"{dim}\" }}\n\
         \n\
         [help]\n\
         on = {{ fg = \"{acc}\" }}\n\
         run = {{ fg = \"{cyn}\" }}\n\
         desc = {{ fg = \"{fg}\" }}\n\
         hovered = {{ reversed = true, bold = true }}\n\
         footer = {{ fg = \"{bg}\", bg = \"{fg}\" }}\n\
         \n\
         [notify]\n\
         title_info = {{ fg = \"{grn}\" }}\n\
         title_warn = {{ fg = \"{yel}\" }}\n\
         title_error = {{ fg = \"{red}\" }}\n\
         \n\
         [filetype]\n\
         rules = [\n\
           {{ mime = \"image/*\", fg = \"{yel}\" }},\n\
           {{ mime = \"video/*\", fg = \"{acc}\" }},\n\
           {{ mime = \"audio/*\", fg = \"{cyn}\" }},\n\
           {{ mime = \"application/zip\", fg = \"{red}\" }},\n\
           {{ mime = \"application/gzip\", fg = \"{red}\" }},\n\
           {{ name = \"*/\", fg = \"{blu}\" }},\n\
         ]\n"
    )
}

fn done(ctx: &ApplyCtx<'_>, d: &str) -> TargetStatus {
    if ctx.dry_run {
        TargetStatus::DryRun {
            summary: d.into(),
        }
    } else {
        TargetStatus::Ok {
            detail: Some(d.into()),
        }
    }
}
