/// Kind of catalogued program.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    Terminal,
    Editor,
    System,
    Compositor,
    Cli,
    Browser,
}

impl Kind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Terminal => "terminal",
            Self::Editor => "editor",
            Self::System => "system",
            Self::Compositor => "compositor",
            Self::Cli => "cli",
            Self::Browser => "browser",
        }
    }

    pub fn uses_terminal_size(self) -> bool {
        matches!(self, Self::Terminal | Self::Editor | Self::Cli)
    }

    pub fn uses_ui_size(self) -> bool {
        matches!(self, Self::System | Self::Compositor | Self::Browser)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Reload {
    None,
    SignalUsr1,
    Gsettings,
    Command(&'static str),
}

/// Built-in adapter. Discovery lists every entry; writers may be missing.
#[derive(Clone, Debug)]
pub struct CatalogEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub kind: Kind,
    pub theme: bool,
    pub font: bool,
    pub size: bool,
    pub binaries: &'static [&'static str],
    pub config_globs: &'static [&'static str],
    pub desktop_ids: &'static [&'static str],
    pub packages: &'static [&'static str],
    pub reload: Reload,
    pub has_writer: bool,
}

impl CatalogEntry {
    pub fn get(id: &str) -> Option<&'static CatalogEntry> {
        all().iter().find(|e| e.id == id)
    }
}

pub fn all() -> &'static [CatalogEntry] {
    CATALOG
}

const CATALOG: &[CatalogEntry] = &[
    // --- system ---
    e(
        "fontconfig",
        "fontconfig",
        Kind::System,
        false,
        true,
        false,
        &[],
        &["~/.config/fontconfig/conf.d/50-irongall.conf"],
        &[],
        &["fontconfig"],
        Reload::None,
        true,
    ),
    e(
        "gtk3",
        "GTK 3",
        Kind::System,
        true,
        true,
        true,
        &[],
        &[
            "~/.config/gtk-3.0/settings.ini",
            "~/.config/gtk-3.0/gtk.css",
        ],
        &[],
        &["gtk3"],
        Reload::None,
        true,
    ),
    e(
        "gtk4",
        "GTK 4",
        Kind::System,
        true,
        true,
        true,
        &[],
        &[
            "~/.config/gtk-4.0/settings.ini",
            "~/.config/gtk-4.0/gtk.css",
        ],
        &[],
        &["gtk4"],
        Reload::None,
        true,
    ),
    e(
        "gsettings",
        "gsettings",
        Kind::System,
        true,
        true,
        true,
        &["gsettings"],
        &[],
        &[],
        &["glib2"],
        Reload::Gsettings,
        true,
    ),
    e(
        "qt6ct",
        "qt6ct",
        Kind::System,
        true,
        true,
        true,
        &["qt6ct"],
        &["~/.config/qt6ct/qt6ct.conf"],
        &["qt6ct.desktop"],
        &["qt6ct"],
        Reload::None,
        true,
    ),
    e(
        "qt5ct",
        "qt5ct",
        Kind::System,
        true,
        true,
        true,
        &["qt5ct"],
        &["~/.config/qt5ct/qt5ct.conf"],
        &["qt5ct.desktop"],
        &["qt5ct"],
        Reload::None,
        true,
    ),
    e(
        "kdeglobals",
        "KDE globals",
        Kind::System,
        true,
        true,
        true,
        &[],
        &["~/.config/kdeglobals"],
        &[],
        &["plasma-workspace"],
        Reload::None,
        true,
    ),
    e(
        "xresources",
        "Xresources",
        Kind::System,
        true,
        false,
        false,
        &[],
        &["~/.Xresources", "~/.Xdefaults"],
        &[],
        &[],
        Reload::Command("xrdb -merge ~/.Xresources"),
        true,
    ),
    e(
        "xsettingsd",
        "xsettingsd",
        Kind::System,
        false,
        true,
        true,
        &["xsettingsd"],
        &[
            "~/.config/xsettingsd/xsettingsd.conf",
            "~/.xsettingsd",
        ],
        &[],
        &["xsettingsd"],
        Reload::Command("pkill -HUP xsettingsd"),
        true,
    ),
    // --- compositor ---
    e(
        "hyprland",
        "Hyprland",
        Kind::Compositor,
        true,
        false,
        false,
        &["Hyprland", "hyprctl"],
        &[
            "~/.config/hypr/hyprland.conf",
            "~/.config/hypr/hyprland.d/*.conf",
        ],
        &[],
        &["hyprland"],
        Reload::Command("hyprctl reload"),
        true,
    ),
    // --- terminals ---
    e(
        "kitty",
        "Kitty",
        Kind::Terminal,
        true,
        true,
        true,
        &["kitty"],
        &["~/.config/kitty/kitty.conf"],
        &["kitty.desktop"],
        &["kitty"],
        Reload::SignalUsr1,
        true,
    ),
    e(
        "ghostty",
        "Ghostty",
        Kind::Terminal,
        true,
        true,
        true,
        &["ghostty"],
        &["~/.config/ghostty/config"],
        &["com.mitchellh.ghostty.desktop", "ghostty.desktop"],
        &["ghostty"],
        Reload::None,
        true,
    ),
    e(
        "alacritty",
        "Alacritty",
        Kind::Terminal,
        true,
        true,
        true,
        &["alacritty"],
        &[
            "~/.config/alacritty/alacritty.toml",
            "~/.config/alacritty/alacritty.yml",
        ],
        &["Alacritty.desktop"],
        &["alacritty"],
        Reload::None,
        true,
    ),
    e(
        "foot",
        "foot",
        Kind::Terminal,
        true,
        true,
        true,
        &["foot"],
        &["~/.config/foot/foot.ini"],
        &["foot.desktop"],
        &["foot"],
        Reload::None,
        true,
    ),
    e(
        "wezterm",
        "WezTerm",
        Kind::Terminal,
        true,
        true,
        true,
        &["wezterm"],
        &[
            "~/.config/wezterm/wezterm.lua",
            "~/.wezterm.lua",
        ],
        &["org.wezfurlong.wezterm.desktop"],
        &["wezterm"],
        Reload::None,
        true,
    ),
    // --- editors ---
    e(
        "neovim",
        "Neovim",
        Kind::Editor,
        true,
        true,
        true,
        &["nvim"],
        &["~/.config/nvim/init.lua", "~/.config/nvim/init.vim"],
        &["nvim.desktop"],
        &["neovim"],
        Reload::None,
        true,
    ),
    e(
        "zed",
        "Zed",
        Kind::Editor,
        true,
        true,
        true,
        &["zed", "zeditor"],
        &["~/.config/zed/settings.json"],
        &["dev.zed.Zed.desktop", "zed.desktop"],
        &["zed"],
        Reload::None,
        true,
    ),
    e(
        "helix",
        "Helix",
        Kind::Editor,
        true,
        false,
        false,
        &["hx"],
        &["~/.config/helix/config.toml"],
        &["Helix.desktop"],
        &["helix"],
        Reload::None,
        true,
    ),
    e(
        "micro",
        "micro",
        Kind::Editor,
        true,
        false,
        false,
        &["micro"],
        &["~/.config/micro/settings.json"],
        &[],
        &["micro"],
        Reload::None,
        true,
    ),
    // --- cli ---
    e(
        "btop",
        "btop",
        Kind::Cli,
        true,
        false,
        false,
        &["btop"],
        &["~/.config/btop/btop.conf"],
        &[],
        &["btop"],
        Reload::None,
        true,
    ),
    e(
        "cava",
        "cava",
        Kind::Cli,
        true,
        false,
        false,
        &["cava"],
        &["~/.config/cava/config"],
        &[],
        &["cava"],
        Reload::None,
        true,
    ),
    e(
        "starship",
        "Starship",
        Kind::Cli,
        true,
        false,
        false,
        &["starship"],
        &["~/.config/starship.toml"],
        &[],
        &["starship"],
        Reload::None,
        true,
    ),
    e(
        "bat",
        "bat",
        Kind::Cli,
        true,
        false,
        false,
        &["bat"],
        &["~/.config/bat/config"],
        &[],
        &["bat"],
        Reload::None,
        true,
    ),
    e(
        "yazi",
        "Yazi",
        Kind::Cli,
        true,
        false,
        false,
        &["yazi"],
        &["~/.config/yazi/theme.toml", "~/.config/yazi/yazi.toml"],
        &[],
        &["yazi"],
        Reload::None,
        true,
    ),
    e(
        "lazygit",
        "lazygit",
        Kind::Cli,
        true,
        false,
        false,
        &["lazygit"],
        &["~/.config/lazygit/config.yml"],
        &[],
        &["lazygit"],
        Reload::None,
        true,
    ),
    e(
        "zathura",
        "Zathura",
        Kind::Cli,
        true,
        true,
        true,
        &["zathura"],
        &["~/.config/zathura/zathurarc"],
        &["org.pwmt.zathura.desktop"],
        &["zathura"],
        Reload::None,
        true,
    ),
    // --- browsers ---
    e(
        "firefox",
        "Firefox",
        Kind::Browser,
        true,
        true,
        true,
        &["firefox"],
        &["~/.mozilla/firefox"],
        &["firefox.desktop"],
        &["firefox"],
        Reload::None,
        false,
    ),
];

const fn e(
    id: &'static str,
    name: &'static str,
    kind: Kind,
    theme: bool,
    font: bool,
    size: bool,
    binaries: &'static [&'static str],
    config_globs: &'static [&'static str],
    desktop_ids: &'static [&'static str],
    packages: &'static [&'static str],
    reload: Reload,
    has_writer: bool,
) -> CatalogEntry {
    CatalogEntry {
        id,
        name,
        kind,
        theme,
        font,
        size,
        binaries,
        config_globs,
        desktop_ids,
        packages,
        reload,
        has_writer,
    }
}

/// System-level adapters that must not take per-app fontconfig aliases.
pub fn is_system_adapter(id: &str) -> bool {
    matches!(
        id,
        "fontconfig" | "gtk3" | "gtk4" | "gsettings" | "qt6ct" | "qt5ct" | "kdeglobals"
            | "xresources" | "xsettingsd"
    )
}
